
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

<?php
    //simple text
?>
<hr>
<p><strong> This is custom text about product from html page</strong></p>



<?php
    //display Custom Block Content(Block Id: custom_block)
    echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('custom_block')->toHtml();
?>




<?php
    $_product = $block->getProduct();
?>

<?php if ($_product->getShortDescription()): ?>
        <div style="margin: 20px 0px">
            <b>Short Description </b><br>
            <?= $_product->getShortDescription() ?>
        </div>
<?php endif;?>


<?php if ($_product->getAttributeText('sales')): ?>
        <div style="margin: 20px 0px">
            <b>Sales: </b><?= $_product->getAttributeText('sales') ?>
        </div>
<?php endif;?>

<hr>