<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <!-- Adding Custom Title as Shipment Info -->
            <!-- <div class="data item title"
                     aria-labeledby="tab-label-shipment-info-title"
                     data-role="collapsible" id="tab-label-shipment-info">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#shipment-info"
                       id="tab-label-shipment-info-title">
                        Shipment Info
                    </a>
            </div>
            <div class="data item content" id="shipment-info" data-role="content">
                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shiping_info')->toHtml();?>
            </div>
             -->
            <!-- add other items -->
            <pre>
                <?php var_dump($detailedInfoGroup)?>
            </pre>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                     data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?= /* @escapeNotVerified */ $alias ?>"
                       id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                        <?= /* @escapeNotVerified */ $label ?>
                    </a>
                </div>
                <div class="data item content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
                    <?= /* @escapeNotVerified */ $html ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>
