<div class="promotional-product">
    
    <div class="promotional-product-image">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('promotional_product_image')->toHtml();?>
    </div>
    
    <div class="promotional-product-title">
         <div><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('promotional_product_title')->toHtml();?></div>
    </div>

    <div class="promotional-product-button-content">
        <button class="promotional-product-button"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('promotionnal_product_button_content')->toHtml();?></button>
    </div>

</div>